version: 2.1

orbs:
  codacy: codacy/base@12.2.0

workflows:
  version: 2
  compile_deploy:
    jobs:
    - codacy/checkout_and_version:
        write_sbt_version: true
    - codacy/sbt:
        name: populate_cache_and_compile
        cmd: sbt +test:compile
        persist_to_workspace: true
        requires:
          - codacy/checkout_and_version
    - codacy/sbt:
        name: checkfmt
        cmd: sbt scalafmtCheckAll
        requires:
          - populate_cache_and_compile
    - codacy/sbt:
        name: test
        cmd: sbt +test
        requires:
          - populate_cache_and_compile
    - codacy/sbt:
        name: publish
        cmd: sbt retrieveGPGKeys +publishSigned sonatypeCentralRelease
        filters:
          branches:
            only:
              - master
        context: CodacyAWS
        requires:
          - test
          - checkfmt
    - codacy/tag_version:
        context: CodacyAWS
        requires:
          - publish
